package com.habiterra.identity.service;

import com.habiterra.identity.dto.*;
import com.habiterra.identity.entity.*;
import com.habiterra.identity.exception.AuthException;
import com.habiterra.identity.repository.*;
import com.habiterra.shared.security.JwtService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.security.SecureRandom;
import java.time.Clock;
import java.time.Instant;


//Service in charge of the OTP
@Service
public class OtpService {

    private static final Logger log =
            LoggerFactory.getLogger(OtpService.class);

    private final IdentifierService identifiers;
    private final IdentifierLock lock;
    private final OtpVerificationRepository otps;
    private final UtilisateurRepository users;
    private final PasswordEncoder encoder;
    private final OtpSender sender;
    private final JwtService tokens;
    private final Clock clock;
//   OTP validity time
    private final long cooldown;
//   Number of requests per hour
    private final int hourlyLimit;
//   Handle dev mode for otp sending
    private final boolean devMode;

//    OTP generated by SecureRandom for security measure
    private final SecureRandom random = new SecureRandom();

    public OtpService(
            IdentifierService identifiers,
            IdentifierLock lock,
            OtpVerificationRepository otps,
            UtilisateurRepository users,
            PasswordEncoder encoder,
            OtpSender sender,
            JwtService tokens,
            Clock clock,
//            Take the value otherwise the default value
            @Value("${auth.otp.cooldown-seconds:60}") long cooldown,
            @Value("${auth.otp.hourly-limit:5}") int hourlyLimit,
            @Value("${auth.otp.dev-mode:false}") boolean devMode
    ) {

        if (cooldown < 1 || hourlyLimit < 1) {
            throw new IllegalArgumentException("Invalid OTP limits");
        }

        this.identifiers = identifiers;
        this.lock = lock;
        this.otps = otps;
        this.users = users;
        this.encoder = encoder;
        this.sender = sender;
        this.tokens = tokens;
        this.clock = clock;
        this.cooldown = cooldown;
        this.hourlyLimit = hourlyLimit;
        this.devMode = devMode;

        log.info("OTP DEV MODE = {}", devMode);
    }

//    Handle the OTP request
    @Transactional
    public RequestOtpResponse request(String input) {

//        Normalize the identifier by retrieving the type and the value
        var id = identifiers.normalize(input);

//Lock the identifier
        lock.acquire(id.value());

//        Verify if the email or phone number doesn't exist in the BD
        var existing = id.type() == IdentifierType.EMAIL
                        ? users.findByEmail(id.value())
                        : users.findByTelephone(id.value());

        if (existing.isPresent()) {
            throw new AuthException(409,
                    id.type() == IdentifierType.EMAIL
                            ? "EMAIL_ALREADY_USED"
                            : "PHONE_ALREADY_USED",
                    "Identifiant deja utilise"
            );
        }

        Instant now = clock.instant();

//        Find the previous OTP that were created for the identifier
        var previous = otps.findFirstByIdentifierAndIdentifierTypeOrderByIdDesc(
                        id.value(),
                        id.type()
                );

//        Verify if the last OTP were sent at least 60s before
        if (
                previous.isPresent() && now.isBefore(previous.get()
                                .getCreatedAt()
                                .plusSeconds(cooldown)
                )
        ) {
            throw new AuthException(429, "OTP_COOLDOWN", "Veuillez patienter avant de demander un nouveau code");
        }
//       Verify the number of OTP that were sent during the hourlyLimit
        if (
                otps.countByIdentifierAndCreatedAtAfter(
                        id.value(),
                        now.minusSeconds(3600)
                ) >= hourlyLimit
        ) {
            throw new AuthException(429, "OTP_RATE_LIMIT", "Limite horaire atteinte");
        }
//         Invalid the last OTP
        previous.ifPresent(
                otp -> otp.setInvalidated(true));

        String code;

//        Generate a new OTP if the previous and the new are similar
        do {
            code = String.format(
                    java.util.Locale.ROOT,
                    "%06d",
                    random.nextInt(1_000_000)
            );
        }
        while (
//                Decode the previous OTP before comparing the two
                previous.isPresent() && encoder.matches(code, previous.get().getCodeHash())
        );

        OtpVerification otp = new OtpVerification();

//        Save the owner of the OTP
        otp.setIdentifier(id.value());
        otp.setIdentifierType(id.type());
        otp.setCodeHash(encoder.encode(code));
        otp.setCreatedAt(now);
        otp.setExpiresAt(now.plusSeconds(300));
        otp.setMaxAttempts(5);

        otps.saveAndFlush(otp);

        /*
         * MODE DEV
         */
        if (devMode) {

            log.warn("Identifier: {}, Code: {}", id.value(), code);

        } else {

            sender.send(id.type(), id.value(), code);
        }

        return new RequestOtpResponse(
                "Code envoye",
                300,
                cooldown
        );
    }

//    Verify the OTP
    @Transactional(noRollbackFor = AuthException.class)
    public VerifyOtpResponse verify(String input, String code) {

        var id = identifiers.normalize(input);

        lock.acquire(id.value());

        OtpVerification otp = otps.findFirstByIdentifierAndIdentifierTypeOrderByIdDesc(
                                id.value(),
                                id.type()
                        )
                        .orElseThrow(
                                () -> new AuthException(
                                        400,
                                        "OTP_NOT_FOUND",
                                        "Code introuvable"
                                )
                        );

//        Invalid OTP cannot be used
        if (otp.isInvalidated()) {
            throw new AuthException(400, "OTP_INVALIDATED", "Code invalide");
        }

//        Verified OTP cannot be used
        if (otp.isVerified()) {
            throw new AuthException(400, "OTP_ALREADY_USED", "Code deja utilise");
        }

//        Expired OTP cannot be used
        if (!otp.getExpiresAt().isAfter(clock.instant())) {
            throw new AuthException(400, "OTP_EXPIRED", "Code expire");
        }

//        Avoid spamming if the cooldown is done
        if (otp.getAttempts() >= otp.getMaxAttempts()) {
            throw new AuthException(429, "OTP_MAX_ATTEMPTS", "Trop de tentatives");
        }

//        If the given OTP is not correct, decrease the attempts number
        if (code == null || !code.matches("[0-9]{6}") || !encoder.matches(code, otp.getCodeHash()))
        {otp.setAttempts(otp.getAttempts() + 1);

            throw new AuthException(otp.getAttempts() >= otp.getMaxAttempts() ? 429
                            : 400, otp.getAttempts() >= otp.getMaxAttempts()
                            ? "OTP_MAX_ATTEMPTS"
                            : "INVALID_OTP",
                    "Code incorrect ou limite atteinte"
            );
        }


//        Otherwise save the otp
        otp.setVerified(true);
        otp.setVerifiedAt(clock.instant());

        return new VerifyOtpResponse(
                tokens.registration(otp),
                true
        );
    }
}