-- Preserve business primary keys, agency assignments and all incoming references.
-- Fail atomically if legacy profiles are attached to incompatible account roles.
LOCK TABLE utilisateur, proprietaire, locataire IN ACCESS EXCLUSIVE MODE;

ALTER TABLE utilisateur ADD CONSTRAINT uk_utilisateur_id_role UNIQUE (id_utilisateur, role);

ALTER TABLE proprietaire
    ADD COLUMN utilisateur_id BIGINT,
    ADD COLUMN utilisateur_role VARCHAR(255) NOT NULL DEFAULT 'PROPRIETAIRE',
    ADD COLUMN prenom VARCHAR(100),
    ADD COLUMN nom VARCHAR(100),
    ADD COLUMN email VARCHAR(100),
    ADD COLUMN telephone VARCHAR(16);
UPDATE proprietaire p SET utilisateur_id = u.id_utilisateur,
    prenom = u.prenom, nom = u.nom, email = u.email, telephone = u.telephone
FROM utilisateur u WHERE p.id_proprietaire = u.id_utilisateur;
ALTER TABLE proprietaire
    ALTER COLUMN prenom SET NOT NULL,
    ALTER COLUMN nom SET NOT NULL,
    ADD CONSTRAINT uk_proprietaire_utilisateur UNIQUE (utilisateur_id),
    ADD CONSTRAINT ck_proprietaire_utilisateur_role CHECK (utilisateur_role = 'PROPRIETAIRE'),
    ADD CONSTRAINT fk_proprietaire_compte FOREIGN KEY (utilisateur_id, utilisateur_role)
        REFERENCES utilisateur(id_utilisateur, role),
    DROP CONSTRAINT fk_proprietaire_users,
    ALTER COLUMN id_proprietaire ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('proprietaire', 'id_proprietaire'),
    COALESCE(MAX(id_proprietaire), 1), MAX(id_proprietaire) IS NOT NULL) FROM proprietaire;

ALTER TABLE locataire
    ADD COLUMN utilisateur_id BIGINT,
    ADD COLUMN utilisateur_role VARCHAR(255) NOT NULL DEFAULT 'LOCATAIRE',
    ADD COLUMN prenom VARCHAR(100),
    ADD COLUMN nom VARCHAR(100),
    ADD COLUMN email VARCHAR(100),
    ADD COLUMN telephone VARCHAR(16);
UPDATE locataire p SET utilisateur_id = u.id_utilisateur,
    prenom = u.prenom, nom = u.nom, email = u.email, telephone = u.telephone
FROM utilisateur u WHERE p.id_locataire = u.id_utilisateur;
ALTER TABLE locataire
    ALTER COLUMN prenom SET NOT NULL,
    ALTER COLUMN nom SET NOT NULL,
    ADD CONSTRAINT uk_locataire_utilisateur UNIQUE (utilisateur_id),
    ADD CONSTRAINT ck_locataire_utilisateur_role CHECK (utilisateur_role = 'LOCATAIRE'),
    ADD CONSTRAINT fk_locataire_compte FOREIGN KEY (utilisateur_id, utilisateur_role)
        REFERENCES utilisateur(id_utilisateur, role),
    DROP CONSTRAINT fk_locataire_users,
    ALTER COLUMN id_locataire ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('locataire', 'id_locataire'),
    COALESCE(MAX(id_locataire), 1), MAX(id_locataire) IS NOT NULL) FROM locataire;
